services:

  client:
    container_name: prakticum-client
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        NODE_VERSION: ${NODE_VERSION}
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - '${EXTERNAL_CLIENT_PORT}:${CLIENT_PORT}'
    depends_on:
      server:
        condition: service_started
    networks:
     - connection

  server:
    container_name: prakticum-server
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        NODE_VERSION: ${NODE_VERSION}
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - connection

  postgres:
    container_name: database
    env_file: .env
    image: postgres:${POSTGRES_VERSION}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      # Update healthcheck comand solving "POSTGRESS | FATAL: role root does not exist"
      # issue: https://github.com/frontandrew/black-jack/pull/135#issuecomment-2319450220
      # solve: https://github.com/docker-library/postgres/issues/838
      test: [ "CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - connection

networks:
  connection:
    driver: bridge

